# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruser',
            options={'verbose_name': 'Raspberry User', 'verbose_name_plural': 'Raspberry Users'},
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=1935),
        ),
    ]
