# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Server', '0003_auto_20170809_1407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('address', 'port')]),
        ),
    ]
