# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Server', '0005_auto_20170809_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=2048),
        ),
    ]
